### ISSUE TITLE
ReadTheDocs Build is not triggered automatically

### ISSUE THREAD

**Issue by hf-kklein** [bo4e/BO4E-python#405]
Upon release [a webhook](https://github.com/bo4e/BO4E-python/settings/hooks/257711588) is sent to readthedocs but readthedocs says it's unhandled.

To build the latest main/most recent version, you need to manually trigger a read-the-docs build.

> GitHub will emit an initial HTTP request (X-GitHub-Event: ping) upon creating the webhook and you may notice that the Read the Docs responds with {"detail":"Unhandled webhook event"} – this is normal and expected. Push changes to your repository and webhooks will work from this point.

https://test-12312.readthedocs.io/en/latest/webhooks.html

**Comment by hf-kklein** [comment]
Problem persists as of v0.4.0

**Comment by hf-kklein** [comment]
> Running Sphinx v6.2.1
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/envs/v0.5.1/lib/python3.10/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/checkouts/v0.5.1/docs/conf.py", line 25, in <module>
    from uml import PlantUMLNetwork, build_network, compile_files_kroki, write_class_umls
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/checkouts/v0.5.1/docs/../docs/uml.py", line 22, in <module>
    from annotated_types import Len, MaxLen, MinLen
ModuleNotFoundError: No module named 'annotated_types'

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/envs/v0.5.1/lib/python3.10/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/envs/v0.5.1/lib/python3.10/site-packages/sphinx/application.py", line 207, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/envs/v0.5.1/lib/python3.10/site-packages/sphinx/config.py", line 177, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/envs/v0.5.1/lib/python3.10/site-packages/sphinx/config.py", line 367, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:
> Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/envs/v0.5.1/lib/python3.10/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/checkouts/v0.5.1/docs/conf.py", line 25, in <module>
    from uml import PlantUMLNetwork, build_network, compile_files_kroki, write_class_umls
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/checkouts/v0.5.1/docs/../docs/uml.py", line 22, in <module>
    from annotated_types import Len, MaxLen, MinLen
ModuleNotFoundError: No module named 'annotated_types'
>  Configuration error:
There is a programmable error in your configuration file:

> Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/envs/v0.5.1/lib/python3.10/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/checkouts/v0.5.1/docs/conf.py", line 25, in <module>
    from uml import PlantUMLNetwork, build_network, compile_files_kroki, write_class_umls
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e-python/checkouts/v0.5.1/docs/../docs/uml.py", line 22, in <module>
    from annotated_types import Len, MaxLen, MinLen
ModuleNotFoundError: No module named 'annotated_types'

https://readthedocs.org/projects/bo4e-python/builds/21265224/

**Comment by hf-kklein** [comment]
next try: #485

**Comment by hf-kklein** [comment]
> Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e/checkouts/latest/docs/conf.py", line 25, in <module>
    from uml import PlantUMLNetwork, build_network, compile_files_kroki, write_class_umls
  File "/home/docs/checkouts/readthedocs.org/user_builds/bo4e/checkouts/latest/docs/../docs/uml.py", line 26, in <module>
    from typeguard import TypeCheckError, check_type
ModuleNotFoundError: No module named 'typeguard'

**Comment by hf-kklein** [comment]
![grafik](https://github.com/bo4e/BO4E-python/assets/23094997/6394129d-b24e-4885-889e-5eff9cc3e15b)

**Comment by lord-haffi** [comment]
Veraltet. Dokumentation wird per GitHub Pages gehosted.
